# Generated by Django 5.2.17 on 2026-09-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("slug", models.SlugField(unique=True)),
                (
                    "excerpt",
                    models.CharField(
                        help_text="Short summary shown on the news list page.",
                        max_length=250,
                    ),
                ),
                ("body", models.TextField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="news/")),
                ("published_at", models.DateTimeField()),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
    ]
