# Generated by Django 5.2.17 on 2026-09-25 18:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("title_en", models.CharField(max_length=150)),
                ("title_uz", models.CharField(max_length=150)),
                ("title_ru", models.CharField(max_length=150)),
                (
                    "excerpt_en",
                    models.CharField(
                        help_text="Short summary shown on the news list page.",
                        max_length=250,
                    ),
                ),
                ("excerpt_uz", models.CharField(max_length=250)),
                ("excerpt_ru", models.CharField(max_length=250)),
                ("body_en", models.TextField()),
                ("body_uz", models.TextField()),
                ("body_ru", models.TextField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="news/")),
                ("published_at", models.DateTimeField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
    ]
