# Generated by Django 5.2.17 on 2026-09-25 18:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HeroSlide",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("title_en", models.CharField(max_length=150)),
                ("title_uz", models.CharField(max_length=150)),
                ("title_ru", models.CharField(max_length=150)),
                ("description_en", models.TextField()),
                ("description_uz", models.TextField()),
                ("description_ru", models.TextField()),
                ("button_name_en", models.CharField(blank=True, max_length=50)),
                ("button_name_uz", models.CharField(blank=True, max_length=50)),
                ("button_name_ru", models.CharField(blank=True, max_length=50)),
                ("button_url", models.CharField(blank=True, max_length=200)),
                ("image", models.ImageField(blank=True, null=True, upload_to="hero/")),
                ("video", models.FileField(blank=True, null=True, upload_to="hero/")),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="WhyChooseUs",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "eyebrow_en",
                    models.CharField(default="Why choose us", max_length=100),
                ),
                (
                    "eyebrow_uz",
                    models.CharField(default="Nega bizni tanlashadi", max_length=100),
                ),
                (
                    "eyebrow_ru",
                    models.CharField(default="Почему выбирают нас", max_length=100),
                ),
                ("heading_en", models.CharField(max_length=200)),
                ("heading_uz", models.CharField(max_length=200)),
                ("heading_ru", models.CharField(max_length=200)),
                ("intro_en", models.TextField()),
                ("intro_uz", models.TextField()),
                ("intro_ru", models.TextField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Why Choose Us section",
                "verbose_name_plural": "Why Choose Us section",
            },
        ),
        migrations.CreateModel(
            name="WhyChooseUsPoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon keyword (truck, clock, warehouse, star, shield, users, document, package, map-pin, dashboard, check, globe)",
                        max_length=50,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="why_us/"),
                ),
                ("title_en", models.CharField(max_length=150)),
                ("title_uz", models.CharField(max_length=150)),
                ("title_ru", models.CharField(max_length=150)),
                ("short_description_en", models.CharField(max_length=250)),
                ("short_description_uz", models.CharField(max_length=250)),
                ("short_description_ru", models.CharField(max_length=250)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points",
                        to="core.whychooseus",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="WhyChooseUsStat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "icon",
                    models.CharField(
                        help_text="truck, clock, warehouse, star, shield, users, document, package, map-pin, dashboard, check, globe",
                        max_length=50,
                    ),
                ),
                (
                    "number",
                    models.CharField(help_text='e.g. "120+" or "99%"', max_length=20),
                ),
                ("label_en", models.CharField(max_length=50)),
                ("label_uz", models.CharField(max_length=50)),
                ("label_ru", models.CharField(max_length=50)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="core.whychooseus",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
