# Generated by Django 5.2.17 on 2026-09-25 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhyChooseUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eyebrow", models.CharField(default="Why choose us", max_length=100)),
                ("heading", models.CharField(max_length=200)),
                ("intro", models.TextField()),
            ],
            options={
                "verbose_name": "Why Choose Us section",
                "verbose_name_plural": "Why Choose Us section",
            },
        ),
        migrations.CreateModel(
            name="WhyChooseUsPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points",
                        to="core.whychooseus",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="WhyChooseUsStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        help_text="truck, clock, warehouse, star, shield, users, document, package, map-pin, dashboard, check, globe",
                        max_length=50,
                    ),
                ),
                (
                    "number",
                    models.CharField(help_text='e.g. "120+" or "99%"', max_length=20),
                ),
                ("label", models.CharField(max_length=50)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="core.whychooseus",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
