# Generated by Django 5.2.17 on 2026-09-25 20:56

import ckeditor.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_seed_why_us"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("title_en", models.CharField(max_length=200)),
                ("title_uz", models.CharField(max_length=200)),
                ("title_ru", models.CharField(max_length=200)),
                (
                    "short_description_en",
                    models.TextField(help_text="Shown on the homepage preview card."),
                ),
                ("short_description_uz", models.TextField()),
                ("short_description_ru", models.TextField()),
                (
                    "full_description_en",
                    ckeditor.fields.RichTextField(
                        help_text="Full write-up shown on the About page."
                    ),
                ),
                ("full_description_uz", ckeditor.fields.RichTextField()),
                ("full_description_ru", ckeditor.fields.RichTextField()),
                (
                    "contact_label_en",
                    models.CharField(
                        blank=True, help_text='e.g. "Contact us"', max_length=50
                    ),
                ),
                ("contact_label_uz", models.CharField(blank=True, max_length=50)),
                ("contact_label_ru", models.CharField(blank=True, max_length=50)),
                ("contact_url", models.CharField(blank=True, max_length=200)),
                ("image", models.ImageField(blank=True, null=True, upload_to="about/")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "About page (company info)",
                "verbose_name_plural": "About page (company info)",
            },
        ),
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact info",
                "verbose_name_plural": "Contact info",
            },
        ),
        migrations.CreateModel(
            name="ContactLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("address_en", models.CharField(max_length=250)),
                ("address_uz", models.CharField(max_length=250)),
                ("address_ru", models.CharField(max_length=250)),
                (
                    "map_url",
                    models.CharField(
                        blank=True, help_text="Optional link to a map.", max_length=300
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "contact_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="core.contactinfo",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Founder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Full name — not translated.", max_length=150
                    ),
                ),
                (
                    "description_en",
                    models.TextField(help_text="What they say about themselves."),
                ),
                ("description_uz", models.TextField()),
                ("description_ru", models.TextField()),
                (
                    "contact",
                    models.CharField(
                        blank=True,
                        help_text="Email, phone, or a social/profile link.",
                        max_length=150,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="founders/"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Full name — not translated.", max_length=150
                    ),
                ),
                (
                    "role_en",
                    models.CharField(
                        help_text='Who they are, e.g. "Fleet Owner, Sunrise Logistics"',
                        max_length=150,
                    ),
                ),
                ("role_uz", models.CharField(max_length=150)),
                ("role_ru", models.CharField(max_length=150)),
                ("feedback_en", models.TextField()),
                ("feedback_uz", models.TextField()),
                ("feedback_ru", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="testimonials/"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
