# Generated by Django 5.2.17 on 2026-09-25 20:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_seed_why_us"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("eyebrow_en", models.CharField(default="About us", max_length=100)),
                (
                    "eyebrow_uz",
                    models.CharField(default="Biz haqimizda", max_length=100),
                ),
                ("eyebrow_ru", models.CharField(default="О нас", max_length=100)),
                ("heading_en", models.CharField(max_length=200)),
                ("heading_uz", models.CharField(max_length=200)),
                ("heading_ru", models.CharField(max_length=200)),
                ("lead_en", models.TextField()),
                ("lead_uz", models.TextField()),
                ("lead_ru", models.TextField()),
                (
                    "story_heading_en",
                    models.CharField(default="Our story", max_length=100),
                ),
                (
                    "story_heading_uz",
                    models.CharField(default="Bizning tariximiz", max_length=100),
                ),
                (
                    "story_heading_ru",
                    models.CharField(default="Наша история", max_length=100),
                ),
                ("story_en", models.TextField()),
                ("story_uz", models.TextField()),
                ("story_ru", models.TextField()),
                (
                    "mission_heading_en",
                    models.CharField(default="Our mission", max_length=100),
                ),
                (
                    "mission_heading_uz",
                    models.CharField(default="Bizning maqsadimiz", max_length=100),
                ),
                (
                    "mission_heading_ru",
                    models.CharField(default="Наша миссия", max_length=100),
                ),
                ("mission_en", models.TextField()),
                ("mission_uz", models.TextField()),
                ("mission_ru", models.TextField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="about/")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "About page",
                "verbose_name_plural": "About page",
            },
        ),
    ]
