# Generated by Django 5.2.17 on 2026-09-29 09:13

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_seed_about_founders_testimonials_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="heroslide",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                storage=core.models.hero_video_storage,
                upload_to="hero/",
            ),
        ),
    ]
