# Generated by Django 5.2.17 on 2026-09-29 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_heroslide_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="heroslide",
            name="description_en",
            field=models.TextField(
                help_text="Keep it short - long text breaks the hero layout.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="heroslide",
            name="description_ru",
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name="heroslide",
            name="description_uz",
            field=models.TextField(max_length=200),
        ),
    ]
