# Generated by Django 5.2.17 on 2026-09-25 18:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("services", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "price_type",
                    models.SlugField(
                        help_text='Internal tier code, e.g. "simple", "standard", "pro". A given service can only have one price per tier.'
                    ),
                ),
                (
                    "price_type_label_en",
                    models.CharField(
                        help_text='Displayed tier name, e.g. "Simple"', max_length=50
                    ),
                ),
                ("price_type_label_uz", models.CharField(max_length=50)),
                ("price_type_label_ru", models.CharField(max_length=50)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("one_time", "One-time"),
                            ("month", "Per month"),
                            ("year", "Per year"),
                        ],
                        default="month",
                        max_length=20,
                    ),
                ),
                (
                    "features_en",
                    models.TextField(
                        blank=True, help_text="One item per line — what's included."
                    ),
                ),
                ("features_uz", models.TextField(blank=True)),
                ("features_ru", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank for a general/standalone price not tied to one service.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "price"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("service__isnull", False)),
                        fields=("service", "price_type"),
                        name="unique_service_price_type",
                    )
                ],
            },
        ),
    ]
