# Generated by Django 5.2.17 on 2026-09-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text='e.g. "nav.home", "btn.learn_more"',
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Where this text appears, for whoever edits it later.",
                        max_length=200,
                    ),
                ),
                ("value_en", models.CharField(max_length=500)),
                ("value_uz", models.CharField(max_length=500)),
                ("value_ru", models.CharField(max_length=500)),
            ],
            options={
                "verbose_name": "Site text",
                "verbose_name_plural": "Site texts",
                "ordering": ["key"],
            },
        ),
    ]
