# Generated by Django 5.2.17 on 2026-09-25 18:53

import ckeditor.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("title_en", models.CharField(max_length=100)),
                ("title_uz", models.CharField(max_length=100)),
                ("title_ru", models.CharField(max_length=100)),
                (
                    "short_name_en",
                    models.CharField(
                        help_text="Short summary shown on cards.", max_length=200
                    ),
                ),
                ("short_name_uz", models.CharField(max_length=200)),
                ("short_name_ru", models.CharField(max_length=200)),
                (
                    "full_info_en",
                    ckeditor.fields.RichTextField(
                        help_text="Full description shown on the service's detail page."
                    ),
                ),
                ("full_info_uz", ckeditor.fields.RichTextField()),
                ("full_info_ru", ckeditor.fields.RichTextField()),
                (
                    "key_points_en",
                    models.TextField(blank=True, help_text="One item per line."),
                ),
                ("key_points_uz", models.TextField(blank=True)),
                ("key_points_ru", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon keyword shown next to the title.",
                        max_length=50,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order", "title_en"],
            },
        ),
        migrations.CreateModel(
            name="ServiceImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("image", models.ImageField(upload_to="services/gallery/")),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="services.service",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
