# Generated by Django 5.2.17 on 2026-09-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_add_fleet_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="services/"),
        ),
        migrations.AddField(
            model_name="service",
            name="key_points",
            field=models.TextField(
                blank=True,
                help_text="One item per line. Shown as a bullet list on the service's detail page.",
            ),
        ),
    ]
