# Generated by Django 5.2.17 on 2026-09-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_seed_systems"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="is_coming_soon",
            field=models.BooleanField(
                default=False,
                help_text='Show a "Coming soon" badge - the service page stays visible, but is marked as not yet available.',
            ),
        ),
    ]
